### ISSUE TITLE
repositories access blocked.......

### ISSUE THREAD

**Issue by BoringLiu** [fgr178707/aliyunpan#4]
**系统版本**
Ubuntu
  22.04.3
  LTS
** JavaScript版本**

**请用文字描述你遇到的问题**
存储库访问锁定是怎么回事呀

**截图**
![image](https://github.com/fgr178707/aliyunpan/assets/76622487/7bff063e-9ed5-4c70-a524-74782b90c9c1)

![image](https://github.com/fgr178707/aliyunpan/assets/76622487/44301080-dc70-42fe-afaa-31f7b82cfeac)

**Comment by fgr178707** [comment]
> **系统版本** Ubuntu 22.04.3 LTS ** JavaScript版本**
> 
> **请用文字描述你遇到的问题** 存储库访问锁定是怎么回事呀
> 
> **截图** ![image](https://user-images.githubusercontent.com/76622487/265460253-7bff063e-9ed5-4c70-a524-74782b90c9c1.png)
> 
> ![image](https://user-images.githubusercontent.com/76622487/265459954-44301080-dc70-42fe-afaa-31f7b82cfeac.png)

github 始大面积封仓库了 仓库跑路吧，已经用不了了

**Comment by BoringLiu** [comment]
所以以后这个就.....没啦？？？ o(╥﹏╥)o 心疼作者

**Comment by fgr178707** [comment]
> 

目前正在用的是金山文档的那个签到  因为最近阿里查的紧，先停一个月，10月1号开启自动签到
你不在电报群里吗?
https://t.me/+zTrZ4ekP4pljNjI9

**Comment by BoringLiu** [comment]
之前布吉岛TOT,现在来啦，谢谢作者！！！
